[package]
distribution = "2024R1"
org = "ballerinax"
name = "notion"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = []
# icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-notion"

[build-options]
observabilityIncluded = true
 